# Generated by Django 3.1.6 on 2021-02-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(max_length=250)),
                ('was_buplished', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=250)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(default=None)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alias.book')),
            ],
        ),
    ]
